### ISSUE TITLE
 New Zend Framework 1 Security Vulnerability - does it apply to this extension?

### ISSUE THREAD

**Issue by madonanragu** [magepal/magento2-gmailsmtpapp#47]
Hi,

Magento has issued a New Zend Framework 1 Security Vulnerability:

https://magento.com/security/news/new-zend-framework-1-security-vulnerability

Does this apply to the M2 extension?

**Comment by srenon** [comment]
Since there is not a lot of information publish on this vulnerability/exploit, I would say "Yes" because 

- This module uses most of the same zend mail components.
- Zend_Mail_Transport_Sendmail/Zend_Mail_Transport_Smtp is essentially a wrapper to the PHP mail() function and still required Sendmail

You could reconfigure your store to match one of the recommended settings. 

![image](https://cloud.githubusercontent.com/assets/1415141/22151452/fee5fe78-deeb-11e6-9ed0-c19cc836192e.png)


It is also possible that the bug only affecting `Zend_Mail_Transport_Sendmail` class which is what magento uses, while this module replaces it with `Zend_Mail_Transport_Smtp`. 

Until more information is provided it is hard for me to give a "yes" or "no" answer.

**Comment by madonanragu** [comment]
Great, thanks so much for clarifying! :)
