### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by jpcsguru** [magepal/magento2-gmailsmtpapp#68]
Hi,
   wat setting do i need to run my mailserver?

**Comment by srenon** [comment]
The same setting you would need to setup iOS Mail, Microsoft Outlook, etc...

**Comment by jpcsguru** [comment]
Are you sure

 

James Purcell

DIRECTOR

 



JPComputer Solutions Pty Ltd

119b edwards Street,Ayr,QLD.4807

Phone 0747836425  

www.jpcomputersolutions.com.au

**Comment by srenon** [comment]
With no technical info or error messages,  I can not be sure about anything. So unless you provide more info I will not be able to help

**Comment by jpcsguru** [comment]
We want to use our mail server not gmail to send our mail so it authenticates using our dkim so it works for gmail and hotmail

 

James Purcell

DIRECTOR

 



JPComputer Solutions Pty Ltd

119b edwards Street,Ayr,QLD.4807

Phone 0747836425  

www.jpcomputersolutions.com.au

**Comment by srenon** [comment]
Server configurations for Gmail, Hotmail, etc are all public information so I know exactly how they are configured. However, your web server and mail server are private servers and I have no knowledge of how it is configured. So without you providing me with error messages or explain what happens when you try to configure it, I will not be able to help you.

You are more than welcome to contact me to set up a paid support option If you just want someone to fix the issue for you without you providing zero information on what the actual problem is.

**Comment by jpcsguru** [comment]
Where is that information btw

 

James Purcell

DIRECTOR

 



JPComputer Solutions Pty Ltd

119b edwards Street,Ayr,QLD.4807

Phone 0747836425  

www.jpcomputersolutions.com.au

**Comment by srenon** [comment]
Please contact support@magepal.com

**Comment by jpcsguru** [comment]
Just a quick not we have got your app functioning on on our magento site.👍
