### ISSUE TITLE
Multi-Store SMTP settings default to primary store

### ISSUE THREAD

**Issue by lee586** [magepal/magento2-gmailsmtpapp#75]
I have Magento 2.1.8 with two stores and two different SMTP settings.  When a customer places an order on either store, the correct SMTP settings are used when the email confirmation is sent by the system.  However, if I send that same email from the ADMIN side by clicking "Send Email" on the order or ship view from the secondary store, it will send the correct email, but it will show has coming from the primary store with it's email settings.  

For example, I have stores ABC.com and XYZ.com.  Each have their own SMTP settings.  If I click on an order from XYZ.com and click, "Send Email," it shows as coming from ABC.com with the ABC store name.

**Comment by srenon** [comment]
@lee586 ... This is a known issue and I will review it shortly.

More than likely Magento is not emulating the store correctly, Therefore it is getting the default store setting see https://github.com/magepal/magento2-gmailsmtpapp/blob/master/Plugin/Mail/TransportPlugin.php#L81

**Comment by lee586** [comment]
I've upgraded to Magento CE 2.2 and the GmailSMTP 1.5.1 but this issue continues to persist.

**Comment by srenon** [comment]
This will not be an easy fix because it is more of a bug in the way Magento 2 is doing things.

If you take a look at M1 they would use `startEnvironmentEmulation($storeId);` so that you can get the correct store id within your code

https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Sales/Model/Order.php#L1293

https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php#L139

**Comment by srenon** [comment]
@lee586 .... this issue should be fixed
