### ISSUE TITLE
DI for magento 2.2 does not work anymore

### ISSUE THREAD

**Issue by brosenberger** [magepal/magento2-gmailsmtpapp#82]
within the DI configuration currently the transport model is set as preference for \Magento\Framework\Mail\Transport. within m2 2.2 the setting changed to the transportinterface: Magento\Framework\Mail\TransportInterface (see mail module https://github.com/magento/magento2/blob/develop/app/code/Magento/Email/etc/di.xml#L11)

**Comment by srenon** [comment]
@brosenberger ... Since they are 2 changes in Magento 2.2, I will need some time to look into this to maintain backward compatibility.

Since they add a new public getMessage() method, the "preference" will not be needed anymore.

Add this to https://github.com/magepal/magento2-gmailsmtpapp/blob/master/etc/di.xml#L12 should work .... (if you have any error comment out line # 9-12)
```
<type name="\Magento\Framework\Mail\TransportInterface">
	<plugin sortOrder="100" name="magePalGmailSmtpAppTransportInterface" type="MagePal\GmailSmtpApp\Plugin\Mail\TransportPlugin"/>
</type>
```

**Comment by srenon** [comment]
Done ... Please test and let me know if you have any issue

https://github.com/magepal/magento2-gmailsmtpapp/releases/tag/1.5.0

**Comment by gvigner** [comment]
Google servers are banned in China, it's not possible to use gmail. Any alternative ?

**Comment by srenon** [comment]
@gvigner .... you can use almost any SMTP server that all you to connect to them.
