### ISSUE TITLE
All emails has one address 

### ISSUE THREAD

**Issue by msliman** [magepal/magento2-gmailsmtpapp#95]
All emails (welcome, orders, shipping) come out from my store to the customers has one address which I set in extension configuration (username). I need to make all store emails are working not the extesnion's one.
I set reply from to NO.

Kindly advice

**Comment by srenon** [comment]
If you are using a third-party email server, the reply email address is set by them.

This extension basically logs into the email account provided and send the email the same way you would log in and send an email. 

When you log into your email a@b.com, can you change it to show that the email is coming from  c@b.com? This will only work if you are using your own mail server.

The way I normally using this extension is to set up a no-reply@company.com to use for the extension and then enable the return path so that if someone replies to the email it will go to the correct sender.
